### ISSUE TITLE
Repeated endpoint description in README.md

### ISSUE THREAD

**Issue by amilano** [kadena-io/chainweb-data#73]
In the file `README.md`, at the list of available [endpoints](https://github.com/kadena-io/chainweb-data#endpoints) the description (`gets the details of a transaction with the given request key`) for the transaction search by request key endpoint, `/txs/tx?requestkey=<request-key>`, is repeated in the events endpoint, `/txs/events?search=foo&limit=20&offset=40`, e.g.:

- `/txs/tx?requestkey=<request-key>` **gets the details of a transaction with the given request key**
- `/txs/events?search=foo&limit=20&offset=40` **gets the details of a transaction with the given request key**

**Comment by enobayram** [comment]
Thanks for opening the issue. [Seems like](https://github.com/kadena-io/chainweb-data#endpoints) it was addressed since then, so I'm closing it.
