### ISSUE TITLE
Disabling -threaded dramatically reduces CPU consumption

### ISSUE THREAD

**Issue by jwiegley** [kadena-io/chainweb-data#91]
I am using a Nix build (GHC 8.10.7) on Intel macOS 11.6.8 (Big Sur).

If I build and run chainweb-data normally, it often uses up to 700% CPU (7 full cores) continuously on my iMac Pro, even when nothing is being done. GHC profiling shows that the executable itself is not doing much work, even over a 24 hour period. Here is the output from that profiling run:

[chainweb-data.prof.zip](https://github.com/kadena-io/chainweb-data/files/9498512/chainweb-data.prof.zip)

This is for a multiple hour run, but you'll see that it reports actual time consumed as being only 2 seconds!

What I've discovered is that if I disable threading in `chainweb-data`, everything still works just fine, but all of the excess CPU utilization completely disappears! So this is the change I make to the cabal file:
```
executable chainweb-data
  import:         commons
  main-is:        Main.hs
  hs-source-dirs: exec
  -- ghc-options:    -threaded -rtsopts -with-rtsopts=-N
  build-depends:
```

I'm creating this issue to suggest that we make this change in chainweb-data if we don't actually need the multi-threaded behavior.

**Comment by enobayram** [comment]
I'm closing this issue because I believe this to be resolved by https://github.com/kadena-io/chainweb-data/pull/148
